### ISSUE TITLE
Microsoft Edge / Images & Links / Notes

### ISSUE THREAD

**Issue by ajtruckle** [ejyothi/MantisBT-MarkDownEditor#1]
Here are my comments so far:

-  On **Internet Explorer 11** and **Firefox** I can see the toolbar when I am creating a new issue. But it does **not** show in the edit box for any **note** that is added and it really **needs** to for the **reporter**.

- On **Microsoft Edge** the toolbar is **not showing** even when I try to add an issue. The link here:
https://simplemde.com/ has it working, so it should work in Edge.

- As for the **IDE** feature, it is nice, but it would be wonderful if it could support **links** and **images**. The https://simplemde.com/ toolbar supports them and the link to the markdown info supports them. But those two toolbar icons are **missing** in MantisBT..

**Comment by libregeek** [comment]
I haven't changed anything with respect to browser compatibility. I just used what is provided by SimpleMDE with some modifications in the toolbar icons. You can see the config in files/plugin.js. We don't use IE or Edge at our workplace, so all of my testing was on Mozilla Firefox and Google Chrome.

For images, we may need to add server-side code to handle attachments. So I thought, for the time being, it's better to use the default file attachment feature in mantis. Mantis has an in-built mechanism to create it's own links to issues, I'm not sure how the links in SimpleMDE will affect Mantis' mechanism. I didn't had much time to think through all the possibilities. These could be added as future enhancements.

I'm away from work for the next couple of weeks and may not have access to the dev environment. So feel free to fork and submit PR.

**Comment by ajtruckle** [comment]
Hi !

Well, I appreciate your kindness in exposing your plugin for the community and I understand that you only use certain browsers at your workplace. But if we are to expose a plugin I would have expected that we now need to widen out our browser support since really it needs to support what MantisBT supports. Otherwise we will get users trying the plugin (like me) and it simply not function.

MantisBT does have links to issues but links are not always provided for that reason. Links to online articles etc. for the reporter to read. Supporting links is not going to affect Mantis in any way and the underlying Markdown already supports them.

The same is true of images. It is the users responsibility to make their image available online somewhere (see the markdown help page for SimpleMDE available from the toolbar). You can already use the markdown manually. The benefit is that you can visually display an image in your issue which saves a user downloading it.

So I think we just need to reinstate those two buttons for links and images.

Thanks for the offer to work on the project. I may have a look but I am not a JavaScript developer so I might leave it.

**Comment by ajtruckle** [comment]
I have noticed that for the description edit window it is kind of locked. So not only no toolbar but no actual edit control is there to click into. The other two edit boxes can be clicked but have no toolbar.

**Comment by libregeek** [comment]
@ajtruckle Could you please confirm whether these issues exist?

**Comment by ajtruckle** [comment]
They do exist. Why I reported it. :) One of my users couldn't use this edit box either on his browser. Sorry!
