### ISSUE TITLE
Stopping popup "error" message

### ISSUE THREAD

**Issue by ajtruckle** [ejyothi/MantisBT-MarkDownEditor#13]
Please remind me how to stop the auto update of the preview area so I don't keep getting the error message box.

Thanks.

**Comment by libregeek** [comment]
Can you please provide a screenshot of the error message?

**Comment by ajtruckle** [comment]
Here you go:

![error](https://user-images.githubusercontent.com/7985331/41771000-ae7d2a20-760b-11e8-9b4d-2c263077cec4.png)

As I keep typing and it auto-updated the preview it does this. The plugin has a timer somewhere for auto refresh and we can comment the code out to stop this.

**Comment by libregeek** [comment]
I couldn't reproduce this error, but I think it's due to the inline images. I can't test it since we don't have such a requirement.

**Comment by ajtruckle** [comment]
I am getting confused here - it must not be your plugin. I use two. Yours and:

Markdown Preview 0.1

________________________________

**Comment by ajtruckle** [comment]
Yes, it was the Markdown Preview plugin.

________________________________
